[versions]
agp = "8.5.1"
compileSdk = "34"
minSdk = "21"
targetSdk = "34"
androidx-activityCompose = "1.9.0"
androidx-material = "1.12.0"
compose = "1.6.8"
compose-plugin = "1.6.11"
kotlin = "2.0.0"
coroutines = "1.8.1"
dokka = "1.9.20"
coil = "3.0.0-alpha08"
coil2 = "2.6.0"
aboutlib = "11.2.2"
markdown = "0.7.3"
detekt = "1.23.6"
gradleMvnPublish = "0.28.0"
screenshot = "0.0.1-alpha02"
ktor = "3.0.0-beta-2"

[libraries]
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlib" }
aboutlibraries-compose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlib" }
coil-core = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor", version.ref = "coil" }
coil2-core = { module = "io.coil-kt:coil-compose", version.ref = "coil2" }
coil2-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil2" }
markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlib" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "gradleMvnPublish" }
screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot" }

[bundles]
coil = ["coil-core", "coil-network-okhttp"]
coil2 = ["coil-core"]
aboutlibs = ["aboutlibraries-core", "aboutlibraries-compose"]